/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tabletennis;

import java.awt.*;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Scanner;
import javax.swing.*;

/**
 *
 * @author jin
 */
public class TableTennisGUI201516Student extends javax.swing.JFrame {

    /**
     * Creates new form TableTennisGUI201516
     */
    private void initHomeAwayComboBox() {
        String homeTeam = (String) homeTeamComboBox.getSelectedItem();
        Team hTeam = (regManager.getATeam(homeTeam));
        String[] playersarray = hTeam.listMembers().toArray(new String[hTeam.listMembers().size()]);

        System.out.println(Arrays.toString(playersarray));

        homePlayer1Combo.setModel(new javax.swing.DefaultComboBoxModel(playersarray));
        homePlayer2Combo.setModel(new javax.swing.DefaultComboBoxModel(playersarray));

        String awayTeam = (String) awayTeamComboBox.getSelectedItem();
        Team aTeam = (regManager.getATeam(awayTeam));
        String[] aplayersarray = aTeam.listMembers().toArray(new String[aTeam.listMembers().size()]);

        System.out.println(Arrays.toString(aplayersarray));

        awayPlayer1Combo.setModel(new javax.swing.DefaultComboBoxModel(aplayersarray));
        awayPlayer2Combo.setModel(new javax.swing.DefaultComboBoxModel(aplayersarray));
    }

    private void initTeamComboBox() {
        ArrayList<String> teamNames = new ArrayList<>();
        for (Team t : regManager.getTeams()) {
            teamNames.add(t.getTname());
        }

        homeTeamComboBox.setModel(new javax.swing.DefaultComboBoxModel(teamNames.toArray()));
        awayTeamComboBox.setModel(new javax.swing.DefaultComboBoxModel(teamNames.toArray()));
        regTeamsCombo.setModel(new javax.swing.DefaultComboBoxModel(teamNames.toArray()));

    }

    private void updatePlayerCombobox() {
        hplayer1 = (String) homePlayer1Combo.getSelectedItem();
        hplayer2 = (String) homePlayer2Combo.getSelectedItem();
        aplayer1 = (String) awayPlayer1Combo.getSelectedItem();
        aplayer2 = (String) awayPlayer2Combo.getSelectedItem();
    }

    public TableTennisGUI201516Student() {
        initComponents();

        Scanner tScan = new Scanner(TableTennisGUI201516Student.class.getResourceAsStream("/teams.txt"));
        Scanner pScan = new Scanner(TableTennisGUI201516Student.class.getResourceAsStream("/players.txt"));

        while (tScan.hasNextLine()) {
            String lineData = tScan.nextLine();
            regManager.createAndAddTeam(lineData);
        }
        tScan.close();

        while (pScan.hasNextLine()) {
            String lineData[] = pScan.nextLine().split(",");
            regManager.createAndAttachPlayer(lineData[1], lineData[0]);
        }
        pScan.close();

        initTeamComboBox();
        initHomeAwayComboBox();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        registrationPanel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        addTeamButton = new javax.swing.JButton();
        regTeamField = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        regTeamsCombo = new javax.swing.JComboBox();
        regPlayerButton = new javax.swing.JButton();
        regPlayerField = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        genFixturesButton = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        teamStatsButton = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        viewerPanel = new javax.swing.JPanel();
        showAllTeamButton = new javax.swing.JButton();
        viewMatchButton = new javax.swing.JButton();
        viewResultButton = new javax.swing.JButton();
        viewerResPanel = new javax.swing.JPanel();
        showTeamRankingButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        viewerTextArea = new javax.swing.JTextArea();
        scoreSheetPanel = new javax.swing.JPanel();
        newSheetButton = new javax.swing.JButton();
        modifySheetButton = new javax.swing.JButton();
        teamNamePanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        homeTeamComboBox = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        awayTeamComboBox = new javax.swing.JComboBox();
        jSeparator1 = new javax.swing.JSeparator();
        setsPanel = new javax.swing.JPanel();
        singleSetsLabel = new javax.swing.JLabel();
        awayPlayer1Combo = new javax.swing.JComboBox();
        awayPlayer2Combo = new javax.swing.JComboBox();
        homePlayer1Combo = new javax.swing.JComboBox();
        h1a1panel = new javax.swing.JPanel();
        h1a1Field1 = new javax.swing.JTextField();
        h1a1Field2 = new javax.swing.JTextField();
        h1a1Field3 = new javax.swing.JTextField();
        h1a2panel = new javax.swing.JPanel();
        h1a2Field1 = new javax.swing.JTextField();
        h1a2Field2 = new javax.swing.JTextField();
        h1a2Field3 = new javax.swing.JTextField();
        homePlayer2Combo = new javax.swing.JComboBox();
        h2a1panel = new javax.swing.JPanel();
        h2a1Field1 = new javax.swing.JTextField();
        h2a1Field2 = new javax.swing.JTextField();
        h2a1Field3 = new javax.swing.JTextField();
        h2a2panel = new javax.swing.JPanel();
        h2a2Field1 = new javax.swing.JTextField();
        h2a2Field2 = new javax.swing.JTextField();
        h2a2Field3 = new javax.swing.JTextField();
        doubleSetLabel1 = new javax.swing.JLabel();
        doublePanel1 = new javax.swing.JPanel();
        doubleField1 = new javax.swing.JTextField();
        doubleField2 = new javax.swing.JTextField();
        doubleField3 = new javax.swing.JTextField();
        teamTotalsField = new javax.swing.JTextField();
        calculateAndSubmitButton = new javax.swing.JButton();
        testButton = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel3.setText("Enter a new team:");

        addTeamButton.setText("Add team");
        addTeamButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addTeamButtonActionPerformed(evt);
            }
        });

        regTeamField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regTeamFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(regTeamField)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addTeamButton)
                .addGap(23, 23, 23))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(addTeamButton)
                    .addComponent(regTeamField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel4.setText("Enter the name of the new player:");

        regTeamsCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select a team name" }));
        regTeamsCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regTeamsComboActionPerformed(evt);
            }
        });

        regPlayerButton.setText("Register player");
        regPlayerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regPlayerButtonActionPerformed(evt);
            }
        });

        regPlayerField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regPlayerFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(regPlayerField, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(regTeamsCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(regPlayerButton)
                .addGap(33, 33, 33))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(regPlayerField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(regTeamsCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(regPlayerButton)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        genFixturesButton.setText("Generate fixtures");
        genFixturesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                genFixturesButtonActionPerformed(evt);
            }
        });

        jLabel5.setText("This will generate a match between all teams.");

        jLabel6.setText("Warning: all pre-existing match information will be removed.");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(genFixturesButton)
                .addGap(33, 33, 33))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(genFixturesButton)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        teamStatsButton.setText("Generate team stats");
        teamStatsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                teamStatsButtonActionPerformed(evt);
            }
        });

        jLabel7.setText("The stats report will be generated automatically every 100 sec.");

        jLabel8.setText("You can also generate it by click the button on the right.");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(18, 18, 18)
                        .addComponent(teamStatsButton))
                    .addComponent(jLabel7))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(teamStatsButton)
                    .addComponent(jLabel8))
                .addGap(28, 28, 28))
        );

        javax.swing.GroupLayout registrationPanelLayout = new javax.swing.GroupLayout(registrationPanel);
        registrationPanel.setLayout(registrationPanelLayout);
        registrationPanelLayout.setHorizontalGroup(
            registrationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(registrationPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(registrationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(60, Short.MAX_VALUE))
        );
        registrationPanelLayout.setVerticalGroup(
            registrationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(registrationPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(142, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Admin page", registrationPanel);

        showAllTeamButton.setText("Show all team stats");
        showAllTeamButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showAllTeamButtonActionPerformed(evt);
            }
        });

        viewMatchButton.setText("View a match scores");
        viewMatchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewMatchButtonActionPerformed(evt);
            }
        });

        viewResultButton.setText("View fixture and result chart");
        viewResultButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewResultButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout viewerResPanelLayout = new javax.swing.GroupLayout(viewerResPanel);
        viewerResPanel.setLayout(viewerResPanelLayout);
        viewerResPanelLayout.setHorizontalGroup(
            viewerResPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 375, Short.MAX_VALUE)
        );
        viewerResPanelLayout.setVerticalGroup(
            viewerResPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        showTeamRankingButton.setText("Show all team ranking");
        showTeamRankingButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showTeamRankingButtonActionPerformed(evt);
            }
        });

        viewerTextArea.setColumns(20);
        viewerTextArea.setRows(5);
        jScrollPane1.setViewportView(viewerTextArea);

        javax.swing.GroupLayout viewerPanelLayout = new javax.swing.GroupLayout(viewerPanel);
        viewerPanel.setLayout(viewerPanelLayout);
        viewerPanelLayout.setHorizontalGroup(
            viewerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(viewerPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(viewerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(viewResultButton)
                    .addComponent(showAllTeamButton, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(showTeamRankingButton)
                    .addComponent(viewMatchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 367, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(viewerResPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        viewerPanelLayout.setVerticalGroup(
            viewerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, viewerPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(viewerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, viewerPanelLayout.createSequentialGroup()
                        .addComponent(viewResultButton)
                        .addGap(18, 18, 18)
                        .addComponent(showAllTeamButton)
                        .addGap(18, 18, 18)
                        .addComponent(showTeamRankingButton)
                        .addGroup(viewerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(viewerPanelLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(viewerResPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap())
                            .addGroup(viewerPanelLayout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addComponent(viewMatchButton)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, viewerPanelLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 407, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(149, 149, 149))))
        );

        jTabbedPane1.addTab("Viewer page", viewerPanel);

        scoreSheetPanel.setBorder(javax.swing.BorderFactory.createCompoundBorder(null, javax.swing.BorderFactory.createEtchedBorder()));

        newSheetButton.setText("New sheet");
        newSheetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newSheetButtonActionPerformed(evt);
            }
        });

        modifySheetButton.setText("Modify sheet");
        modifySheetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modifySheetButtonActionPerformed(evt);
            }
        });

        jLabel1.setText("Home team");
        teamNamePanel.add(jLabel1);

        homeTeamComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Home Team" }));
        homeTeamComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeTeamComboBoxActionPerformed(evt);
            }
        });
        teamNamePanel.add(homeTeamComboBox);

        jLabel2.setText("Away team");
        teamNamePanel.add(jLabel2);

        awayTeamComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Away Team" }));
        awayTeamComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                awayTeamComboBoxActionPerformed(evt);
            }
        });
        teamNamePanel.add(awayTeamComboBox);

        setsPanel.setLayout(new java.awt.GridLayout(4, 3, 1, 3));

        singleSetsLabel.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        singleSetsLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        singleSetsLabel.setText("Single Sets");
        setsPanel.add(singleSetsLabel);

        awayPlayer1Combo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "away player" }));
        awayPlayer1Combo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                awayPlayer1ComboActionPerformed(evt);
            }
        });
        setsPanel.add(awayPlayer1Combo);

        awayPlayer2Combo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "away player" }));
        awayPlayer2Combo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                awayPlayer2ComboActionPerformed(evt);
            }
        });
        setsPanel.add(awayPlayer2Combo);

        homePlayer1Combo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "home player" }));
        homePlayer1Combo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homePlayer1ComboActionPerformed(evt);
            }
        });
        setsPanel.add(homePlayer1Combo);

        h1a1panel.setLayout(new java.awt.GridLayout(0, 1));

        h1a1Field1.setText("0:0");
        h1a1Field1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                h1a1Field1ActionPerformed(evt);
            }
        });
        h1a1panel.add(h1a1Field1);

        h1a1Field2.setText("0:0");
        h1a1panel.add(h1a1Field2);

        h1a1Field3.setText("0:0");
        h1a1panel.add(h1a1Field3);

        setsPanel.add(h1a1panel);

        h1a2panel.setLayout(new java.awt.GridLayout(0, 1));

        h1a2Field1.setText("0:0");
        h1a2Field1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                h1a2Field1ActionPerformed(evt);
            }
        });
        h1a2panel.add(h1a2Field1);

        h1a2Field2.setText("0:0");
        h1a2panel.add(h1a2Field2);

        h1a2Field3.setText("0:0");
        h1a2Field3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                h1a2Field3ActionPerformed(evt);
            }
        });
        h1a2panel.add(h1a2Field3);

        setsPanel.add(h1a2panel);

        homePlayer2Combo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "home player" }));
        homePlayer2Combo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homePlayer2ComboActionPerformed(evt);
            }
        });
        setsPanel.add(homePlayer2Combo);

        h2a1panel.setLayout(new java.awt.GridLayout(0, 1));

        h2a1Field1.setText("0:0");
        h2a1Field1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                h2a1Field1ActionPerformed(evt);
            }
        });
        h2a1panel.add(h2a1Field1);

        h2a1Field2.setText("0:0");
        h2a1panel.add(h2a1Field2);

        h2a1Field3.setText("0:0");
        h2a1panel.add(h2a1Field3);

        setsPanel.add(h2a1panel);

        h2a2panel.setLayout(new java.awt.GridLayout(0, 1));

        h2a2Field1.setText("0:0");
        h2a2Field1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                h2a2Field1ActionPerformed(evt);
            }
        });
        h2a2panel.add(h2a2Field1);

        h2a2Field2.setText("0:0");
        h2a2panel.add(h2a2Field2);

        h2a2Field3.setText("0:0");
        h2a2panel.add(h2a2Field3);

        setsPanel.add(h2a2panel);

        doubleSetLabel1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        doubleSetLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        doubleSetLabel1.setText("Double set");
        setsPanel.add(doubleSetLabel1);

        doublePanel1.setLayout(new java.awt.GridLayout(0, 1));

        doubleField1.setText("0:0");
        doubleField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doubleField1ActionPerformed(evt);
            }
        });
        doublePanel1.add(doubleField1);

        doubleField2.setText("0:0");
        doublePanel1.add(doubleField2);

        doubleField3.setText("0:0");
        doublePanel1.add(doubleField3);

        setsPanel.add(doublePanel1);

        teamTotalsField.setText("Final team scores");
        teamTotalsField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                teamTotalsFieldActionPerformed(evt);
            }
        });
        setsPanel.add(teamTotalsField);

        calculateAndSubmitButton.setText("Calculate and submit scores");
        calculateAndSubmitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculateAndSubmitButtonActionPerformed(evt);
            }
        });

        testButton.setBackground(new java.awt.Color(204, 255, 204));
        testButton.setText("Test scores");
        testButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                testButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout scoreSheetPanelLayout = new javax.swing.GroupLayout(scoreSheetPanel);
        scoreSheetPanel.setLayout(scoreSheetPanelLayout);
        scoreSheetPanelLayout.setHorizontalGroup(
            scoreSheetPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(scoreSheetPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(scoreSheetPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(teamNamePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 466, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(scoreSheetPanelLayout.createSequentialGroup()
                        .addComponent(newSheetButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(modifySheetButton))
                    .addGroup(scoreSheetPanelLayout.createSequentialGroup()
                        .addComponent(setsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 406, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(testButton, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(calculateAndSubmitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 406, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        scoreSheetPanelLayout.setVerticalGroup(
            scoreSheetPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(scoreSheetPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(scoreSheetPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(newSheetButton)
                    .addComponent(modifySheetButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(teamNamePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(scoreSheetPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(setsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(testButton, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(calculateAndSubmitButton)
                .addContainerGap(132, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Score Sheet", scoreSheetPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 606, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 67, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 599, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 9, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void regPlayerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regPlayerButtonActionPerformed
        String pname = regPlayerField.getText();
        String tname = (String) regTeamsCombo.getSelectedItem();

        regManager.createAndAttachPlayer(tname, pname);
        initHomeAwayComboBox();
    }//GEN-LAST:event_regPlayerButtonActionPerformed

    private void newSheetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newSheetButtonActionPerformed
        clearScoreSheet();
        // TODO add your handling code here:
    }//GEN-LAST:event_newSheetButtonActionPerformed

    private void showAllTeamButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showAllTeamButtonActionPerformed

    }//GEN-LAST:event_showAllTeamButtonActionPerformed

    private void homeTeamComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeTeamComboBoxActionPerformed
        initHomeAwayComboBox();
    }//GEN-LAST:event_homeTeamComboBoxActionPerformed

    private void awayTeamComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_awayTeamComboBoxActionPerformed
        initHomeAwayComboBox();
    }//GEN-LAST:event_awayTeamComboBoxActionPerformed

    private void h1a1Field1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_h1a1Field1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_h1a1Field1ActionPerformed

    private void h1a2Field1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_h1a2Field1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_h1a2Field1ActionPerformed

    private void h2a1Field1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_h2a1Field1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_h2a1Field1ActionPerformed

    private void h2a2Field1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_h2a2Field1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_h2a2Field1ActionPerformed

    private void h1a2Field3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_h1a2Field3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_h1a2Field3ActionPerformed

    private void homePlayer1ComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homePlayer1ComboActionPerformed
        hplayer1 = (String) homePlayer1Combo.getSelectedItem();

    }//GEN-LAST:event_homePlayer1ComboActionPerformed

    private void doubleField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doubleField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_doubleField1ActionPerformed

    private void viewResultButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewResultButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_viewResultButtonActionPerformed


    private void calculateAndSubmitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calculateAndSubmitButtonActionPerformed
        String hTeam = (String) homeTeamComboBox.getSelectedItem();
        String aTeam = (String) awayTeamComboBox.getSelectedItem();

        populateScoresArray();
        updatePlayerCombobox();

        Match m = fixtures.getAMatch(hTeam, aTeam);

        m.sethPlayer1(hplayer1);
        m.sethPlayer2(hplayer2);
        m.setaPlayer1(aplayer1);
        m.setaPlayer2(aplayer2);

        m.setScoreSet(scoreSet);

        System.out.println(hplayer1 + " " + hplayer2 + " " + aplayer1 + " " + aplayer2);

        int si = -1;
        for (Set s : m.getSets()) {

            s.enterSetScore((scoreSet[++si]), (scoreSet[++si]),
                    (scoreSet[++si]), (scoreSet[++si]),
                    (scoreSet[++si]), (scoreSet[++si]));

        }

        m.calculateScores();
        teamTotalsField.setText(Integer.toString(m.gethTeamWin()) + ":" + Integer.toString(m.getaTeamWin()));


    }//GEN-LAST:event_calculateAndSubmitButtonActionPerformed

    private void populateScoresArray() {
        scoreSet[0] = getFirst(h1a1Field1.getText()); //h1
        scoreSet[1] = getSecond(h1a1Field1.getText()); //a1
        scoreSet[2] = getFirst(h1a1Field2.getText()); //h2
        scoreSet[3] = getSecond(h1a1Field2.getText()); //a2
        scoreSet[4] = getFirst(h1a1Field3.getText()); //h3
        scoreSet[5] = getSecond(h1a1Field3.getText()); //a3

        scoreSet[6] = getFirst(h1a2Field1.getText());
        scoreSet[7] = getSecond(h1a2Field1.getText());
        scoreSet[8] = getFirst(h1a2Field2.getText());
        scoreSet[9] = getSecond(h1a2Field2.getText());
        scoreSet[10] = getFirst(h1a2Field3.getText());
        scoreSet[11] = getSecond(h1a2Field3.getText());

        scoreSet[12] = getFirst(h2a1Field1.getText());
        scoreSet[13] = getSecond(h2a1Field1.getText());
        scoreSet[14] = getFirst(h2a1Field2.getText());
        scoreSet[15] = getSecond(h2a1Field2.getText());
        scoreSet[16] = getFirst(h2a1Field3.getText());
        scoreSet[17] = getSecond(h2a1Field3.getText());

        scoreSet[18] = getFirst(h2a2Field1.getText());
        scoreSet[19] = getSecond(h2a2Field1.getText());
        scoreSet[20] = getFirst(h2a2Field2.getText());
        scoreSet[21] = getSecond(h2a2Field2.getText());
        scoreSet[22] = getFirst(h2a2Field3.getText());
        scoreSet[23] = getSecond(h2a2Field3.getText());

        scoreSet[24] = getFirst(doubleField1.getText());
        scoreSet[25] = getSecond(doubleField1.getText());
        scoreSet[26] = getFirst(doubleField2.getText());
        scoreSet[27] = getSecond(doubleField2.getText());
        scoreSet[28] = getFirst(doubleField3.getText());
        scoreSet[29] = getSecond(doubleField3.getText());
    }

    private int getFirst(String input) {
        String[] parts = input.split(":");
        return Integer.parseInt(parts[0]);
    }

    private int getSecond(String input) {
        String[] parts = input.split(":");
        return Integer.parseInt(parts[1]);
    }

    private void genFixturesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_genFixturesButtonActionPerformed
        fixtures.generateFixtures(regManager);
        fixtures.showFixtures();
        // TODO add your handling code here:
    }//GEN-LAST:event_genFixturesButtonActionPerformed

    private void addTeamButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addTeamButtonActionPerformed
        String tname = regTeamField.getText();
        //teams.add(tname);
        regManager.createAndAddTeam(tname);
        initTeamComboBox();

    }//GEN-LAST:event_addTeamButtonActionPerformed

    private void homePlayer2ComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homePlayer2ComboActionPerformed
        hplayer2 = (String) homePlayer2Combo.getSelectedItem();
    }//GEN-LAST:event_homePlayer2ComboActionPerformed

    private void awayPlayer1ComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_awayPlayer1ComboActionPerformed
        aplayer1 = (String) awayPlayer1Combo.getSelectedItem();


    }//GEN-LAST:event_awayPlayer1ComboActionPerformed

    private void awayPlayer2ComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_awayPlayer2ComboActionPerformed
        aplayer2 = (String) awayPlayer2Combo.getSelectedItem();
    }//GEN-LAST:event_awayPlayer2ComboActionPerformed

    private void testButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_testButtonActionPerformed
        if (!sc.hasNext()) {
            return;
        } else {

            h1a1Field1.setText(sc.nextLine());
            h1a1Field2.setText(sc.nextLine());
            h1a1Field3.setText(sc.nextLine());

            h1a2Field1.setText(sc.nextLine());
            h1a2Field2.setText(sc.nextLine());
            h1a2Field3.setText(sc.nextLine());

            h2a1Field1.setText(sc.nextLine());
            h2a1Field2.setText(sc.nextLine());
            h2a1Field3.setText(sc.nextLine());

            h2a2Field1.setText(sc.nextLine());
            h2a2Field2.setText(sc.nextLine());
            h2a2Field3.setText(sc.nextLine());

            doubleField1.setText(sc.nextLine());
            doubleField2.setText(sc.nextLine());
            doubleField3.setText(sc.nextLine());
        }

        sc.nextLine();

    }//GEN-LAST:event_testButtonActionPerformed

    private void clearScoreSheet() {

        String zeros = "0:0";

        h1a1Field1.setText(zeros);
        h1a1Field2.setText(zeros);
        h1a1Field3.setText(zeros);

        h1a2Field1.setText(zeros);
        h1a2Field2.setText(zeros);
        h1a2Field3.setText(zeros);

        h2a1Field1.setText(zeros);
        h2a1Field2.setText(zeros);
        h2a1Field3.setText(zeros);

        h2a2Field1.setText(zeros);
        h2a2Field2.setText(zeros);
        h2a2Field3.setText(zeros);

        doubleField1.setText(zeros);
        doubleField2.setText(zeros);
        doubleField3.setText(zeros);
        teamTotalsField.setText(zeros);

    }

    private void modifySheetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modifySheetButtonActionPerformed
        //ask for home team, away team
        String hteam = JOptionPane.showInputDialog("Enter the home team");
        String ateam = JOptionPane.showInputDialog("Enter the away team");

        homeTeamComboBox.setSelectedItem(hteam);
        awayTeamComboBox.setSelectedItem(ateam);

        Match m = fixtures.getAMatch(hteam, ateam);

        initHomeAwayComboBox();
        updatePlayerCombobox();
        updateFields(m.getScoreSet());
        teamTotalsField.setText(Integer.toString(m.gethTeamWin()) + ":" + Integer.toString(m.getaTeamWin()));
    }//GEN-LAST:event_modifySheetButtonActionPerformed

    private void updateFields(int[] scores) {
        h1a1Field1.setText(concat(scores[0], scores[1]));
        h1a1Field2.setText(concat(scores[2], scores[3]));
        h1a1Field2.setText(concat(scores[4], scores[5]));

        h1a2Field1.setText(concat(scores[6], scores[7]));
        h1a2Field2.setText(concat(scores[8], scores[9]));
        h1a2Field3.setText(concat(scores[10], scores[11]));

        h2a1Field1.setText(concat(scores[12], scores[13]));
        h2a1Field2.setText(concat(scores[14], scores[15]));
        h2a1Field3.setText(concat(scores[16], scores[17]));

        h2a2Field1.setText(concat(scores[18], scores[19]));
        h2a2Field2.setText(concat(scores[20], scores[21]));
        h2a2Field3.setText(concat(scores[22], scores[23]));

        doubleField1.setText(concat(scores[24], scores[25]));
        doubleField2.setText(concat(scores[26], scores[27]));
        doubleField3.setText(concat(scores[28], scores[29]));
    }

    private String concat(int a, int b) {
        return (Integer.toString(a) + ":" + Integer.toString(b));
    }

    private void viewMatchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewMatchButtonActionPerformed
        String hteam = JOptionPane.showInputDialog("Enter the home team");
        String ateam = JOptionPane.showInputDialog("Enter the away team");
        // TODO add your handling code here:

    }//GEN-LAST:event_viewMatchButtonActionPerformed

    private void teamStatsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_teamStatsButtonActionPerformed
        ReportGenerator r = new ReportGenerator(fixtures);
        r.generateTeamStats();

    }//GEN-LAST:event_teamStatsButtonActionPerformed

    private void regTeamsComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regTeamsComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_regTeamsComboActionPerformed

    private void regTeamFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regTeamFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_regTeamFieldActionPerformed

    private void showTeamRankingButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showTeamRankingButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_showTeamRankingButtonActionPerformed

    private void regPlayerFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regPlayerFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_regPlayerFieldActionPerformed

    private void teamTotalsFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_teamTotalsFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_teamTotalsFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TableTennisGUI201516Student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TableTennisGUI201516Student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TableTennisGUI201516Student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TableTennisGUI201516Student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TableTennisGUI201516Student().setVisible(true);
            }
        });

    }

    // The following are some of my own variables. You may not need these. Or you may need some other variables.
    //variables for the system
    Fixtures fixtures = new Fixtures();
    RegistrationManager regManager = new RegistrationManager();
    ReportGenerator report = new ReportGenerator(fixtures);

    //variables for temporary usages
    private String hplayer1;
    private String hplayer2;
    private String aplayer1;
    private String aplayer2;

    private int[] scoreSet = new int[30];

    //"testscores.txt" contans some game points. This save the tester to enter the points manually.
    public Scanner sc = new Scanner(TableTennisGUI201516Student.class.getResourceAsStream("/testscores.txt"));

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addTeamButton;
    private javax.swing.JComboBox awayPlayer1Combo;
    private javax.swing.JComboBox awayPlayer2Combo;
    private javax.swing.JComboBox awayTeamComboBox;
    private javax.swing.JButton calculateAndSubmitButton;
    private javax.swing.JTextField doubleField1;
    private javax.swing.JTextField doubleField2;
    private javax.swing.JTextField doubleField3;
    private javax.swing.JPanel doublePanel1;
    private javax.swing.JLabel doubleSetLabel1;
    private javax.swing.JButton genFixturesButton;
    private javax.swing.JTextField h1a1Field1;
    private javax.swing.JTextField h1a1Field2;
    private javax.swing.JTextField h1a1Field3;
    private javax.swing.JPanel h1a1panel;
    private javax.swing.JTextField h1a2Field1;
    private javax.swing.JTextField h1a2Field2;
    private javax.swing.JTextField h1a2Field3;
    private javax.swing.JPanel h1a2panel;
    private javax.swing.JTextField h2a1Field1;
    private javax.swing.JTextField h2a1Field2;
    private javax.swing.JTextField h2a1Field3;
    private javax.swing.JPanel h2a1panel;
    private javax.swing.JTextField h2a2Field1;
    private javax.swing.JTextField h2a2Field2;
    private javax.swing.JTextField h2a2Field3;
    private javax.swing.JPanel h2a2panel;
    private javax.swing.JComboBox homePlayer1Combo;
    private javax.swing.JComboBox homePlayer2Combo;
    private javax.swing.JComboBox homeTeamComboBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JButton modifySheetButton;
    private javax.swing.JButton newSheetButton;
    private javax.swing.JButton regPlayerButton;
    private javax.swing.JTextField regPlayerField;
    private javax.swing.JTextField regTeamField;
    private javax.swing.JComboBox regTeamsCombo;
    private javax.swing.JPanel registrationPanel;
    private javax.swing.JPanel scoreSheetPanel;
    private javax.swing.JPanel setsPanel;
    private javax.swing.JButton showAllTeamButton;
    private javax.swing.JButton showTeamRankingButton;
    private javax.swing.JLabel singleSetsLabel;
    private javax.swing.JPanel teamNamePanel;
    private javax.swing.JButton teamStatsButton;
    private javax.swing.JTextField teamTotalsField;
    private javax.swing.JButton testButton;
    private javax.swing.JButton viewMatchButton;
    private javax.swing.JButton viewResultButton;
    private javax.swing.JPanel viewerPanel;
    private javax.swing.JPanel viewerResPanel;
    private javax.swing.JTextArea viewerTextArea;
    // End of variables declaration//GEN-END:variables
}
